// <auto-generated />
namespace EducationEFMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedPhoneandEmailtostudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPhoneandEmailtostudent));
        
        string IMigrationMetadata.Id
        {
            get { return "201709181548374_added Phone and Email to student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
